### ISSUE TITLE
Create a plan for backend

### ISSUE THREAD

**Issue by Hankier** [hqrEdu/ZeroToJuniorMapBravo#1]
Prepare a plan for backend.

Include what technologies will be used.

DoD:
Initial plan is created.
Task are described.

**Comment by Aspink** [comment]
The aim of the project is to create a simple application that shows on the map where Z2J participants live.

Input: Form -> discord nickname, place of residence (initially - city, zip code, country).
Output: Map with dots representing where Z2J participants live.
Optional -> Find the closest people from Z2J to arrange a coffee or coding together.

Initial backend stack:
Java 17, JDBC, PostgreSQL database, connecting to the frontend via REST API.

Initial plan/task list:

1. Create database 
2. Init project
3. Create model class
4. Connect db to the project
5. Map objects from java to records in db
