### ISSUE TITLE
Create a plan for frontend

### ISSUE THREAD

**Issue by Hankier** [hqrEdu/ZeroToJuniorMapBravo#2]
Prepare a plan for frontend.

Include what technologies will be used.

DoD:
Initial plan is created.
Task are described.

**Comment by lukas-python** [comment]
The project will use HTML, CSS, JavaScript in the frontend dimension. 

From the frontend libraries Bootstrap will be used. 

In the first step, mockups will be created with the layout of individual tabs. 
Then a visualization of the page will be prepared using canva. 
In the next step, tasks will be distributed among people involved in FE.
